name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install mdBook
      run: cargo install mdbook

    - name: Prepare src directory
      run: |
        mkdir -p src/vulnerabilities
        cp README.md src/SUMMARY.md
        cp -r vulnerabilities/* src/vulnerabilities/
        ls -la src
        ls -la src/vulnerabilities

    - name: Build the book
      run: mdbook build src

    - name: List docs directory
      run: ls -la src/book

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
