name: Deploy Main to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install mdBook
      run: cargo install mdbook

    - name: Prepare src directory
      run: |
        mkdir -p src/vulnerabilities
        cp README.md src/README.md  # Set README.md as the index page

        # Create the SUMMARY.md with a reference to index.md
        # echo "# Summary" > src/SUMMARY.md
        echo "[Introduction](README.md)" > src/SUMMARY.md

        # Add vulnerabilities section
        echo "- [Vulnerabilities](vulnerabilities/README.md)" >> src/SUMMARY.md
        for file in vulnerabilities/*.md; do
          filename=$(basename $file)
          echo "  - [${filename%.*}](${file})" >> src/SUMMARY.md
        done

        # Copy vulnerabilities content
        cp -r vulnerabilities/* src/vulnerabilities/
        ls -la src

    - name: Build the book
      run: mdbook build

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Copy built book to gh-pages
      run: |
        rm -rf gh-pages/docs
        mkdir -p gh-pages/docs
        cp -r book/* gh-pages/docs/

    - name: List output after copying
      run: |
        ls -alh src/
        ls -alh gh-pages/docs/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd gh-pages
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs
        git commit -m 'Deploy new changes'
        git push origin gh-pages
