name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install mdBook
      run: cargo install mdbook

    - name: Prepare src directory
      run: |
        mkdir -p src/vulnerabilities
        cp README.md src/SUMMARY.md
        cp -r vulnerabilities/* src/vulnerabilities/

    - name: List src directory
      run: ls -la src

    - name: List vulnerabilities directory
      run: ls -la src/vulnerabilities

    - name: Build the book
      run: mdbook build src

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Copy built book to gh-pages
      run: |
        rm -rf docs
        mkdir docs
        cp -r src/book/* docs/

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs
        git commit -m 'Update documentation'
        git push origin gh-pages
