name: Doppler OIDC Test
on:
  push:
    branches: [main]
jobs:
  fetch-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get GitHub OIDC Token
        id: oidc
        run: |
          OIDC_TOKEN=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/oidc/token" | jq -r '.value')
          echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
          echo "GitHub OIDC Token: $OIDC_TOKEN"
      - name: Authenticate with Doppler
        run: |
          RESPONSE=$(curl --request POST \
            --url https://api.doppler.com/v3/auth/oidc \
            --header 'Content-Type: application/json' \
            --data "{\"identity\": \"2fa28312-5f5d-4767-8025-6a3732bd1842\", \"token\": \"$OIDC_TOKEN\"}")
          echo "Doppler Response: $RESPONSE"
          DOPPLER_TOKEN=$(echo $RESPONSE | jq -r '.token')
          echo "Doppler API Token: $DOPPLER_TOKEN"
          echo "DOPPLER_TOKEN=$DOPPLER_TOKEN" >> $GITHUB_ENV
      - name: Test Doppler API
        run: |
          curl --request GET \
            --url https://api.doppler.com/v3/configs/config/secrets/download?format=json \
            --header "Authorization: Bearer $DOPPLER_TOKEN"
